### PR TITLE
Added PortalHooks.php

### PR DESCRIPTION
**Pull request by Underdog-01**
This is the onset of the long overdo hooks.
There are still several pending.

Signed-off-by: Chen Zhen <github.underdog@gmail.com>

### CODE REVIEW

**Comment by Underdog-01** [comment]
I forgot to update the beginning of the file to show all the functions.
This can be done later.

**Comment by Underdog-01** [comment]
I can't remember now but is the help text is only for admin?

If that is the case then we can just put some logic before the language file call to check if user is an admin & if the user is in the admin section. 

Let me know.

**Comment by Underdog-01** [comment]
Alright, I'm done for now until you review and/or test/tweak those changes.

**Comment by Underdog-01** [comment]
The redirect is not working properly at the moment... when I test the function contents in a PHP block, the output is correct (using echo to see the variable) but when I test it with redirectexit() it is missing the "index.php?' ... I will have to fix it.

**Comment by Underdog-01** [comment]
I'm fairly sure you'll likely figure out a more optimal solution for the redirect.
I tested a few scenarios but not any using pages or standalone mode therefore those will have to be done to see if it works as intended.

**Comment by silentguardian** [comment]
Thanks for the great work. I'll review this in the next couple of days.

**Comment by Underdog-01** [comment]
Sounds good.
There are probably more hooks we can use.
Sometimes you have to look at a SMF function that is called just prior to one of your inserts where the end of that function will have a hook.  We might be able to eliminate even more file edits given that type of scenario. 

Also when this version is finished and the next one for SMF 2.1 is under way, there are more hooks to use for that branch. At some point they stopped developing SMF 2.0 so only "fixes" are being released so any newer hooks that were introduced are only in the newer branch.

If you only want to make minor changes here & there to what I just introduced I suggest accepting this PR and then just make additional changes as new PR's.

After this has gone through I can start on eliminating the HTML tables.
Do you want DIV css table structure (display: table, table-row, table-cell, etc..) or DIV blocks with floats (< left & right float) and margin (<- margin 0 auto for the middle)? Those are the only 2 ways I know to get the tabular effect.

**Comment by Underdog-01** [comment]
FYI - DIV tables are the way to go.
Then add css to adapt the display for mobile.
My experience with the ported version of SP brought me to the conclusion that it's best to detect mobile display/browser with PHP. Then you have the blocks appear one on top of the other also give the admin the option of using each block for mobile/desktop/both so they can decide what to show on mobile. Yes, it's possible to have client-side -> server side -> client side to detect mobile in PHP.

**Comment by Spuds** [comment]
I cherry picked most of this into https://github.com/SimplePortal/SimplePortal/commit/efd24634223ba3be780130cb58cd59412766ebed

**Pull request closed without merging**
